Repository LARP2023Z/LARPex, pull requests merged in 2023-11, with the labels that each got.

#39 feat-arch: sequence diagrams fix
  arch/arch_design.gaphor
Labels: documentation, architecture

#38 feat-arch: add updated test scenarios for use cases
  test/acceptance-test-scenarios.md
Labels: testing

#43 feat-be: Bootstrap users
  .github/workflows/user-identity-service.yaml
  user-identity-be/.gitignore
  user-identity-be/Dockerfile
  user-identity-be/build.gradle
  user-identity-be/compose.yaml
  user-identity-be/gradle/wrapper/gradle-wrapper.jar
  user-identity-be/gradle/wrapper/gradle-wrapper.properties
  user-identity-be/gradlew
  user-identity-be/gradlew.bat
  user-identity-be/settings.gradle
  user-identity-be/src/main/java/pl/larp/larpex/usi/UsiApplication.java
  user-identity-be/src/main/java/pl/larp/larpex/usi/user/adapter/api/UserDetailsController.java
  user-identity-be/src/main/java/pl/larp/larpex/usi/user/adapter/memory/InMemoryUsersRepository.java
  user-identity-be/src/main/java/pl/larp/larpex/usi/user/domain/model/User.java
  user-identity-be/src/main/java/pl/larp/larpex/usi/user/domain/model/UserCredential.java
  user-identity-be/src/main/java/pl/larp/larpex/usi/user/domain/model/UserDetailResponse.java
  user-identity-be/src/main/java/pl/larp/larpex/usi/user/domain/port/IUsers.java
  user-identity-be/src/main/java/pl/larp/larpex/usi/user/domain/port/UserService.java
  user-identity-be/src/main/resources/application.yaml
  user-identity-be/src/test/java/pl/larp/larpex/usi/user/adapter/api/UserDetailsControllerUnitTest.java
  user-identity-be/src/test/java/pl/larp/larpex/usi/user/adapter/memory/InMemoryUsersFixtures.java
  user-identity-be/src/test/java/pl/larp/larpex/usi/user/domain/port/UserServiceIntegrationTest.java
Labels: backend

#73 feat-arch: vpp migration
  arch/LARPex.vpp
  arch/event-frontend-class-diagram-14.11.gaphor
  arch/event-frontend-class-diagram-2.gaphor
  arch/payment_fe.gaphor
  arch/vpp-xml/data.zip
  arch/vpp-xml/project.xml
Labels: documentation, architecture
